language: node_js

node_js:
    - '4.5.0'

before_install:
    - npm install -g mocha

script:
    - npm run cover

# Send coverage data to Coveralls
after_script:
    - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
